apiVersion: apps/v1
kind: Gateway
metadata:
  name: category
  labels:
    app: category
spec:
  replicas: 1
  selector:
    matchLabels:
      app: category
  template:
    metadata:
      labels:
        app: category
    spec:
      containers:
        - name: category
          image: maithanhson/demo-k8s:category_image  # Thay thế bằng image bạn đã xây dựng
          ports:
            - containerPort: 8080  # Cổng mà ứng dụng lắng nghe
